config/routes.rb
SimpleFormBootstrap::Application.routes.draw do
  devise_for :users
  
  namespace :admin do
    resources :users
  end
  resources :communities do
    get :autocomplete_community_name, :on => :collection
  end
  resources :uses, :features, :jobs, :project_categories, :soil_test_result_types, :soil_test_result_units

  resources :projects do
    resources :attachments, :path => '/:target_type/:target_id/attachments'
  end
  resources :sites do
    resources :patches, :soils
  end
  resources :soils do
    resources :soil_tests
  end

  resources :briefs do
    namespace :goals do
      resources :yields do
        get :autocomplete_use_name, :on => :collection
      end
      resources :features do
        get :autocomplete_feature_name, :on => :collection
      end
      resources :labour_inputs do
        get :autocomplete_job_name, :on => :collection
      end
      resources :budget_items do
        get :autocomplete_budget_category_name, :on => :collection
      end
    end
  end

  # mount Forem::Engine, :at => "/forums"

  match 'home', :to => 'home#index'
  root :to => 'home#index'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :project
  belongs_to :target, :polymorphic => true

  file_accessor :file
  validates_presence_of :file, :project
  
  def name
    title.blank? ? filename : title
  end
  
  def filename
    file.name if file
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < InheritedResources::Base
  belongs_to :project
  before_filter :load_scope
  load_and_authorize_resource
  before_filter :target

  create! do |success, failure|
    success.html { redirect_to attachment_return_url }
  end  
  
  update! do |success, failure|
    success.html { redirect_to attachment_return_url }
  end  

  destroy! do |success, failure|
    success.html { redirect_to attachment_return_url }
  end  
  
  private
  
    def end_of_association_chain
      target.attachments
    end
  
    def load_scope
      if params[:scope_id]
        @scope = AttachmentScope.find(params[:scope_id])
      end
    end
    
    def target
      @target ||= load_target
    end
    
    def load_target
      raise ArgumentError unless params[:target_type]
      raise ArgumentError unless params[:target_id]
      
      target_class = params[:target_type].classify.constantize
      target_class.find(params[:target_id])
    end

    def resource_params
      result = super
      result[0][:project] = parent
      result
    end
    
    def attachment_return_url
      if @target
        @target
      elsif parent
        project_attachments_path(parent)
      else
        attachments_path
      end
    end
    helper_method :attachment_return_url

end

app/helpers/attachments_helper.rb
module AttachmentsHelper
  def attach_file_button(resource)
    link_url = new_project_attachment_path(attachment_keys(resource))
    link_to 'Attach File', link_url, :class => 'btn'
  end
  
  def manage_attachments_link(resource)
    link_to 'Manage Attachments', project_attachments_path(attachment_keys(resource))
  end
  
  def attachment_keys(resource, attachment = nil)
    resource_type = resource.class.name.underscore.to_sym
    result = {:project_id => resource.project.to_param, :target_id => resource.to_param, :target_type => resource_type}
    result[:id] = attachment.to_param if attachment
    result
  end
  
  def attachments_container_link
    if @target
      ' ' + content_tag(:small, link_to("Back to #{@target.name}", @target))
    end
  end
  
  def attachments_mini_table
    if !resource.attachments.empty?
      render :partial => 'attachments/mini_table', :locals => {:attachments => resource.attachments, :target => resource}
    end
  end

  def file_link_with_icon(text, file)
    if file
      link_to file.url, :class => 'file_link' do
        image_tag(file_icon_url(file), :class => 'file_icon') +
        content_tag(:span, text + " (#{file.format.to_s})", :class => "file_link_description")        
      end
    end
  end
  
  def file_icon_link(file, options = {})
    if file
      link_to file.url, :class => 'file_link' do
        image_tag(file_icon_url(file, options), :class => 'file_icon', :alt => file.format)
      end
    end
  end
  
  def file_icon_url(file, options = {})
    if file.format
      image_formats = %w(png jpg gif)
      format_string = file.format.to_s.downcase
      
      vendor_images_path = Rails.root.join("vendor/assets/images")
      icon_path = "file-type-icons/file_icons/small/#{format_string}.png"
      
      if options[:display_image] && image_formats.include?(format_string)
        return file.thumb('34x34#').url
      elsif File.exists?(vendor_images_path.join(icon_path))
        return icon_path
      end
    end
    nil
  end
end

app/views/attachments/_form.html.haml
= simple_form_for [@project, @scope, @attachment], :html => {:multipart => true} do |f|
  = form_errors(f)
  .inputs
    = f.input :title
    = f.hidden_field :retained_file
    = f.input :file, :as => :file
    = f.input :description, :input_html => { :class => "span8", :rows => 3 }
  = form_actions(f)

app/views/attachments/_mini_table.html.haml
%table.zebra-striped.bordered-table
  %tbody
    - attachments.each do |attachment|
      %tr
        %td{:style => 'width: 1px'}
          = file_icon_link(attachment.file, :display_image => true)
        %td
          = link_to(attachment.name, attachment.file.url)
          .details
            = truncate(attachment.description, :length => 150)
  - if can? :manage, Attachment
    %tfoot
      %tr
        %td.table_actions{:colspan => 2}
          = manage_attachments_link(@target || target)

app/views/attachments/_table.html.haml
= table_for(collection) do |t|
  = t.data do
    = t.cell(:icon, :heading => '', :cell_html => {:style => 'width: 1px'}) {|attachment| file_icon_link(attachment.file) }
    = t.cell('File') {|attachment| link_to(attachment.name, attachment.file.url) }
    = t.cell('Description', :cell_html => {:class => 'details'}) {|attachment| truncate(attachment.description, :length => 200) }
    - if can? :edit, @project
      = t.cell(:edit, :heading => '', :cell_html => {:class => 'actions'}) do |attachment|
        - link_to('Edit', edit_project_attachment_path(attachment_keys(@target, attachment)))
      = t.cell(:remove, :heading => '', :cell_html => {:class => 'actions'}) do |attachment| 
        - link_to('Remove', project_attachment_path(attachment_keys(@target, attachment)), :confirm => 'Are you sure?', :method => :delete)

app/views/attachments/index.html.haml
= top_available_heading ("Listing #{resource_title.pluralize}" + attachments_container_link).html_safe
.well
  = link_to "New #{resource_title}", {:action => :new}, :class => 'btn'
= render :partial => 'table'