config/routes.rb
SimpleFormBootstrap::Application.routes.draw do
  devise_for :users
  
  namespace :admin do
    resources :users
  end
  resources :communities do
    get :autocomplete_community_name, :on => :collection
  end
  resources :uses, :features, :jobs, :project_categories, :soil_test_result_types, :soil_test_result_units

  resources :projects do
    resources :attachments, :path => '/:target_type/:target_id/attachments'
  end
  resources :sites do
    resources :patches, :soils
  end
  resources :soils do
    resources :soil_tests
  end

  resources :briefs do
    namespace :goals do
      resources :yields do
        get :autocomplete_use_name, :on => :collection
      end
      resources :features do
        get :autocomplete_feature_name, :on => :collection
      end
      resources :labour_inputs do
        get :autocomplete_job_name, :on => :collection
      end
      resources :budget_items do
        get :autocomplete_budget_category_name, :on => :collection
      end
    end
  end

  # mount Forem::Engine, :at => "/forums"

  match 'home', :to => 'home#index'
  root :to => 'home#index'
end

app/models/project.rb
require 'unit'

class Project < ActiveRecord::Base
  CLIMATE_ZONES = %w(tropical sub-tropical temperate cool-temperate arid arctic)
  CURRENCIES = %w(USD AUD NZD EUR GBP)
  
  image_accessor :photo

  has_one :brief, :dependent => :destroy
  has_one :site, :dependent => :destroy
  belongs_to :project_category
  has_many :attachments, :dependent => :destroy
  has_many :project_collaborators, :dependent => :destroy
  has_many :project_communities, :dependent => :destroy
  has_many :communities, :through => :project_communities, :uniq => true
  
  accepts_nested_attributes_for :project_collaborators, :allow_destroy => true
  accepts_nested_attributes_for :project_communities, :allow_destroy => true
  
  geocoded_by :address
  after_validation :geocode

  validates_presence_of :name, :address, :project_category
  validates_inclusion_of :climate_zone, :in => CLIMATE_ZONES, :allow_blank => true
  validates_inclusion_of :site_area_unit, :in => Unit::LAND_AREA_UNITS, :allow_blank => true
  validates_inclusion_of :preferred_currency, :in => Money::Currency::TABLE.map {|row| row.last[:iso_code]}, :allow_blank => true
  validates_inclusion_of :preferred_measures, :in => Unit::SYSTEMS_OF_MEASURE, :allow_blank => true
  validates_numericality_of :site_area, :allow_nil => true
  validates_associated :project_collaborators
  validate :must_have_owner
  validate :must_have_unique_collaborators

  has_amount_with_unit :name => :site_area
  can_assign_by_name :project_category
  
  after_create :create_dependencies
  
  scope :all_public, where(:is_public => true)
  
  def user
    first_collaborator = project_collaborators.owners.first
    first_collaborator.user if first_collaborator
  end
  
  def user=(value)
    self.project_collaborators << ProjectCollaborator.new(:project_role => 'owner', :user => value, :project => self)
    value
  end

  def display_name
    name
  end
  
  def hemisphere
    if latitude && longitude
      latitude >= 0 ? 'northern' : 'southern'
    end
  end
  
  def currency
    Money::Currency.new(preferred_currency)
  rescue Money::Currency::UnknownCurrency
    Money.default_currency
  end
  
  def owner_names
    project_collaborators.owners.map(&:user_name).to_sentence
  end
  
  def brief_id
    brief.id
  end
  
  protected

    def prevent_geocoding?
      address.blank? || (!latitude.blank? && !longitude.blank?) || ['test', 'cucumber'].include?(Rails.env)
    end
    
    def create_dependencies
      create_brief!
      create_site!
    end
    
    def must_have_owner
      remaining_owners = project_collaborators.reject do |collaborator|
        collaborator.marked_for_destruction? || collaborator.project_role != 'owner'
      end
      if remaining_owners.empty?
        errors.add(:project_collaborators, "must include at least one owner")
      end
    end
    
    def must_have_unique_collaborators
      remaining_users = project_collaborators.reject(&:marked_for_destruction?).map(&:user)
      if remaining_users.uniq.length < remaining_users.length
        errors.add(:project_collaborators, "can only include each person once")
      end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  load_and_authorize_resource
  
  add_crumb("Projects") { |instance| instance.send :projects_path }
  add_crumb(lambda {|instance| instance.resource_display_name}, :only => [:show, :edit, :update])
  add_crumb('New Project', :only => [:new, :create])
  
  def resource_display_name
    resource.display_name
  end
  
  protected
  
    def build_resource
      get_resource_ivar || set_resource_ivar(build_new_resource)
    end
    
    def build_new_resource
      result = end_of_association_chain.send(method_for_build, *resource_params)
      result.user = current_user if result.project_collaborators.empty?
      result
    end
  
end

app/helpers/project_helper.rb
module ProjectHelper
  def project_link(project)
    if can?(:read, project)
      link_to project.name, project
    else
      content_tag(:span, project.name)
    end
  end
  
  def project_access_level(project)
    if can?(:edit, project)
      'editable'
    elsif can?(:read, project)
      'readable'
    else
      'private'
    end
  end  
end

app/views/projects/_form.html.haml
= simple_form_for @project, :html => {:multipart => true} do |f|
  = form_errors(f)
  = field_set_tag "Project Details" do
    = f.input :name, :hint => "add your project title here"
    = f.association :project_category, :label => 'Category'
    = f.input :address, :hint => "If you don't have an address, list a nearby town"
    = f.input :site_area, :as => :amount_with_unit
    = f.input :climate_zone, :as => :inferred_select
    = f.input :description, :as => :text, :hint => "A very short description of your desired outcomes", :input_html => {:rows => 5}
    = f.input :photo, :as => :image, :label => '"Before" photo'
  = field_set_tag "Project Settings" do
    = f.input :preferred_currency, :label => 'Currency', :as => :select, :collection => Money::Currency::TABLE.map {|row| [row.last[:name], row.last[:iso_code]]}.sort, :allow_blank => true
    = f.input :preferred_measures, :label => 'Measurements', :as => :inferred_select
    = f.input :is_public, :as => :select
    = render :partial => 'project_collaborators_subform', :locals => {:f => f}
    = render :partial => 'project_communities_subform', :locals => {:f => f}

  .actions
    = f.button :submit, :class => 'primary'
    = link_to 'Cancel', @project, :class => "btn"

= todo("Set initial currency and measures from Country")

app/views/projects/_mini_table.html.haml
%table
  %tbody
    - collection.each do |project|
      %tr
        %td
          .project_name= project_link project
          - if show_access
            .role= '(' + project_access_level(project) + ')'
        %td= project.owner_names

app/views/projects/_project_collaborator_fields.html.haml
%tr.nested-fields{:class => (f.object.errors.empty? ? nil : 'nested-record-with-errors')}
  %td
    = f.input_field :user_id, :as => :select, :collection => User.all
    = f.error :user
    = f.error :user_id
  %td
    = f.input_field :project_role, :as => :select, :collection => ProjectCollaborator::PROJECT_ROLES
    = f.error :project_role    
  %td.action
    = link_to_remove_association "Remove", f

app/views/projects/_project_collaborators_subform.html.haml
.nested_form.clearfix
  %label.nested_form_label Collaborators
  = f.full_error :project_collaborators, :class => 'nested-form-error'
  %table.nested_form_contents.form-stacked.zebra-striped.bordered-table{:class => (f.object.errors[:project_collaborators].empty? ? nil : 'nested-records-with-errors')}
    %thead
      %tr
        %th User
        %th Project role <abbr title="required">*</abbr>
        %th
    %tbody#project_collaborators
      = f.simple_fields_for :project_collaborators, :wrapper => :horizontal do |collab|
        = render 'project_collaborator_fields', :f => collab
    %tfoot
      %tr
        %td.table_actions{:colspan => 3}
          = link_to_add_association 'Add a collaborator', f, :project_collaborators, :'data-association-insertion-node' => '#project_collaborators', :'data-association-insertion-method' => 'append'

app/views/projects/_project_communities_subform.haml
.nested_form.clearfix
  %label.nested_form_label Communities
  = f.full_error :project_communities, :class => 'nested-form-error'
  %table.nested_form_contents.form-stacked.zebra-striped.bordered-table{:class => (f.object.errors[:project_communities].empty? ? nil : 'nested-records-with-errors')}
    %thead
      %tr
        %th Community name
        %th This community can <abbr title="required">*</abbr>
        %th
    %tbody#project_communities
      = f.simple_fields_for :project_communities, :wrapper => :horizontal do |collab|
        = render 'project_community_fields', :f => collab
    %tfoot
      %tr
        %td.table_actions{:colspan => 3}
          = link_to_add_association 'Add a community', f, :project_communities, :'data-association-insertion-node' => '#project_communities', :'data-association-insertion-method' => 'append'

app/views/projects/_project_communities_subform.html.haml
.nested_form.clearfix
  %label.nested_form_label Communities
  = f.full_error :project_communities, :class => 'nested-form-error'
  %table.nested_form_contents.form-stacked.zebra-striped.bordered-table{:class => (f.object.errors[:project_communities].empty? ? nil : 'nested-records-with-errors')}
    %thead
      %tr
        %th Community name
        %th This community can <abbr title="required">*</abbr>
        %th
    %tbody#project_communities
      = f.simple_fields_for :project_communities, :wrapper => :horizontal do |collab|
        = render 'project_community_fields', :f => collab
    %tfoot
      %tr
        %td.table_actions{:colspan => 3}
          = link_to_add_association 'Add a community', f, :project_communities, :'data-association-insertion-node' => '#project_communities', :'data-association-insertion-method' => 'append'

app/views/projects/_project_community_fields.haml
%tr.nested-fields{:class => (f.object.errors.empty? ? nil : 'nested-record-with-errors')}
  %td
    - if f.object && !f.object.new_record? && f.object.community
      = link_to f.object.community_name, f.object.community, :confirm => "If you leave this page to visit the community page, your changes on this form will be lost."
    - else
      = f.input_field :community_name, :as => :autocomplete, :url => autocomplete_community_name_communities_path
    = f.error :community_name
  %td
    .access_level
      = f.input_field(:access, :as => :select, :collection => ProjectCommunity::ACCESS_LEVELS)
      %span.add-on
        your project
    = f.error :access
  %td.action
    = link_to_remove_association "Remove", f

app/views/projects/_table.html.haml
= table_for(collection) do |t|
  = t.data do
    = t.cell :name
    = t.cell :user, :heading => 'Owner'
    = t.cell(:view, :heading => '', :cell_html => {:class => 'actions'}) {|project| link_to('View', project) }
    = t.cell(:edit, :heading => '', :cell_html => {:class => 'actions'}) {|project| link_to('Edit', edit_project_path(project)) }
    = t.cell(:remove, :heading => '', :cell_html => {:class => 'actions'}) {|project| link_to('Remove', project, :confirm => 'Are you sure?', :method => :delete) }

app/views/projects/new.html.haml
%h1 Create your project
.row
  .span11
    = render 'form'
  .span5
    .page_explanation
      %h2 Welcome to Habitat
      %p
        Fill out this form to create your new project.
      %p
        Creating a project lets you start planning your garden. You can keep the information
        to yourself, you can share it with selected other people (such as friends,
        garden designers, etc), or you can share you progress with the whole world.
      %p
        Some features of Habitat will eventually require a paid account, but even
        just using the free features, we think that you'll find Habitat useful
        in planning your garden project.

app/views/projects/show.html.haml
%article
  .content
    %header
      %h1
        = @project.name
    - if can? :edit, @project
      .well
        = link_to "Edit Details", edit_project_path(@project), :class => 'btn'
        / = link_to "Attach File", edit_project_path(@project), :class => 'btn'
    .row
      .span10
        %table
          %thead
            %tbody
              = attribute_row(@project, :project_category, :label => 'Category')
              - unless @project.address.blank?
                %tr
                  %td
                    %strong Address
                  %td= @project.address
                %tr
                  %td
                    %strong Lat / Lon
                  %td= "#{@project.latitude} / #{@project.longitude}"
                = attribute_row(@project, :hemisphere)
                = attribute_row(@project, :site_area_with_unit, :label => 'Size')
                = attribute_row(@project, :climate_zone)
                = attribute_row(@project, :description)              
                - if @project.photo_uid
                  %tr
                    %td
                      %strong Before
                    %td
                      = single_image_grid @project.photo
      .span6
        - if @project.latitude
          = project_map(@project)
          
        %h2 Collaborators
        = render :partial => 'project_collaborators/mini_table', :locals => {:project_collaborators => @project.project_collaborators}

        - unless @project.project_communities.empty?
          %h2 Communities
          = render :partial => 'project_communities/mini_table', :locals => {:project_communities => @project.project_communities}

        