config/routes.rb
SimpleFormBootstrap::Application.routes.draw do
  devise_for :users
  
  namespace :admin do
    resources :users
  end
  resources :communities do
    get :autocomplete_community_name, :on => :collection
  end
  resources :uses, :features, :jobs, :project_categories, :soil_test_result_types, :soil_test_result_units

  resources :projects do
    resources :attachments, :path => '/:target_type/:target_id/attachments'
  end
  resources :sites do
    resources :patches, :soils
  end
  resources :soils do
    resources :soil_tests
  end

  resources :briefs do
    namespace :goals do
      resources :yields do
        get :autocomplete_use_name, :on => :collection
      end
      resources :features do
        get :autocomplete_feature_name, :on => :collection
      end
      resources :labour_inputs do
        get :autocomplete_job_name, :on => :collection
      end
      resources :budget_items do
        get :autocomplete_budget_category_name, :on => :collection
      end
    end
  end

  # mount Forem::Engine, :at => "/forums"

  match 'home', :to => 'home#index'
  root :to => 'home#index'
end

app/models/brief.rb
class Brief < ActiveRecord::Base
  belongs_to :project
  
  has_many :attachments, :as => :target
  has_many :yields, :dependent => :destroy, :class_name => 'Goals::Yield'
  has_many :labour_inputs, :dependent => :destroy, :class_name => 'Goals::LabourInput'
  has_many :budget_items, :dependent => :destroy, :class_name => 'Goals::BudgetItem'
  has_many :features, :dependent => :destroy, :class_name => 'Goals::Feature'
  
  def name
    "#{project.name} Brief" if project
  end
end

app/controllers/briefs_controller.rb
class BriefsController < InheritedResources::Base
  load_and_authorize_resource
  actions :show, :edit, :update
  before_filter :load_project
  
  private
  
    def load_project
      @project = resource.project
    end
end

app/views/briefs/_form.html.haml
= simple_form_for resource do |f|
  = form_errors(f)
  .inputs
    = f.input :description, :label => 'Overview', :hint => "Optional additional text describing your project goals", :input_html => {:rows => 10}
  = form_actions(f, resource)

app/views/briefs/show.html.haml
%h1 Your Goals
- if can? :edit, @brief
  .well
    = link_to 'Edit Overview', {:action => :edit}, :class => 'btn'
    = attach_file_button(@brief)
    = link_to 'New Yield', new_brief_goals_yield_path(@brief), :class => 'btn'
    = link_to 'New Feature', new_brief_goals_feature_path(@brief), :class => 'btn'
    = link_to 'New Labour Input', new_brief_goals_labour_input_path(@brief), :class => 'btn'
    = link_to 'New Budget Item', new_brief_goals_budget_item_path(@brief), :class => 'btn'
.row
  .span10
    #brief
      %table
        %thead
          %tbody
            = attribute_row(@brief, :description, :label => 'Overview', :line_breaks => true)
            - if !@brief.attachments.empty?
              %tr
                %td
                  %strong Attachments
                %td
                  = render :partial => 'attachments/mini_table', :locals => {:attachments => @brief.attachments, :target => @brief}
            
    
    - if can?(:edit, @brief) || !@brief.yields.empty?
      #yields
        %h2 
          Yields
          %small What do you want to be able to harvest?
        %br
        = render :partial => 'goals/yields/table', :locals => {:yields => @brief.yields}
    
    - if can?(:edit, @brief) || !@brief.features.empty?
      #features
        %h2 
          Features
          %small Non-quantifiable characteristics of your garden
        %br
        = render :partial => 'goals/features/table', :locals => {:features => @brief.features}

    - if can?(:edit, @brief) || !@brief.labour_inputs.empty?
      #labour_inputs
        %h2
          Labour Inputs
          %small How much work do you want to have to put in?
        %br
        = render :partial => 'goals/labour_inputs/table', :locals => {:labour_inputs => @brief.labour_inputs}

    - if can?(:edit, @brief) || !@brief.budget_items.empty?
      #budget_items
        %h2
          Budget
          %small Finances broken down by project stage
        %br
        = render :partial => 'goals/budget_items/table', :locals => {:budget_items => @brief.budget_items}
    
  .span6
    - if can? :edit, Project
      .page_explanation
        %h2 What are you Building?
        %p
          It's important to have some goals in mind before you get started on design. These goals, collected together
          with any other supporting documentation, make up your design brief.
        %p
          You could use your design brief to explain what you want designed to a professional permaculture designer,
          but even if you are doing all the design yourself, you'll want to be able to check back here regularly to see
          if your plan is going to achieve the goals you had in mind.