config/routes.rb
SimpleFormBootstrap::Application.routes.draw do
  devise_for :users
  
  namespace :admin do
    resources :users
  end
  resources :communities do
    get :autocomplete_community_name, :on => :collection
  end
  resources :uses, :features, :jobs, :project_categories, :soil_test_result_types, :soil_test_result_units

  resources :projects do
    resources :attachments, :path => '/:target_type/:target_id/attachments'
  end
  resources :sites do
    resources :patches, :soils
  end
  resources :soils do
    resources :soil_tests
  end

  resources :briefs do
    namespace :goals do
      resources :yields do
        get :autocomplete_use_name, :on => :collection
      end
      resources :features do
        get :autocomplete_feature_name, :on => :collection
      end
      resources :labour_inputs do
        get :autocomplete_job_name, :on => :collection
      end
      resources :budget_items do
        get :autocomplete_budget_category_name, :on => :collection
      end
    end
  end

  # mount Forem::Engine, :at => "/forums"

  match 'home', :to => 'home#index'
  root :to => 'home#index'
end

app/models/goals/yield_goal.rb
require 'unit'

class Goals::YieldGoal < ActiveRecord::Base
  SPECIAL_USE_UNITS = %w(varieties)
  
  belongs_to :project
  belongs_to :use
  
  validates_presence_of :project, :use, :use_name
  validates_numericality_of :amount, :lead_time_in_years, :allow_blank => true, :greater_than => 0
  validates_inclusion_of :amount_unit, :in => Unit::COMMON_VOLUME_UNITS + Unit::COMMON_WEIGHT_UNITS + SPECIAL_USE_UNITS, :allow_blank => true
  validates_inclusion_of :amount_period, :in => Unit::CALENDAR_TIME_UNITS, :allow_blank => true

  can_assign_by_name :use
  has_amount_with_period
  
  def lead_time_string
    Unit.format_amount_and_unit(lead_time_in_years, 'year', :pluralize_unit => true)
  end
end

app/models/yield_goal.rb
require 'unit'

class YieldGoal < ActiveRecord::Base
  SPECIAL_USE_UNITS = %w(varieties)
  
  belongs_to :project
  belongs_to :use
  
  validates_presence_of :project, :use, :use_name
  validates_numericality_of :amount, :lead_time_in_years, :allow_blank => true, :greater_than => 0
  validates_inclusion_of :amount_unit, :in => Unit::COMMON_VOLUME_UNITS + Unit::COMMON_WEIGHT_UNITS + SPECIAL_USE_UNITS, :allow_blank => true
  validates_inclusion_of :amount_period, :in => Unit::CALENDAR_TIME_UNITS, :allow_blank => true

  can_assign_by_name :use
  has_amount_with_period
  
  def lead_time_string
    Unit.format_amount_and_unit(lead_time_in_years, 'year', :pluralize_unit => true)
  end
end

app/controllers/goals/yield_goals_controller.rb
class Goals::YieldGoalsController < InheritedResources::Base
  autocomplete :use, :name
  
  load_and_authorize_resource
  belongs_to :project
  
  actions :all, :except => :show
  
  def index
    redirect_to project_goals_path(@project)
  end
end

app/controllers/yield_goals_controller.rb
class YieldGoalsController < InheritedResources::Base
  autocomplete :use, :name
  
  load_and_authorize_resource
  belongs_to :project
  
  actions :all, :except => :show
  
  def index
    redirect_to project_goals_path(@project)
  end
end

app/views/yield_goals/_form.html.haml
= simple_form_for [@project, @yield_goal], :wrapper => :inline, :html => {:multipart => true} do |f|
  = form_errors(f)
  .inputs
    = f.input :use_name, :label => 'Product', :as => :autocomplete, :url => autocomplete_use_name_project_yield_goals_path
    = f.input :amount, :as => :amount_per_period
    = f.input :lead_time_in_years, :as => :string_with_add_on, :suffix => "years", :label => "Lead time", :input_html => {:class => 'mini'}
    = f.input :details, :input_html => {:rows => 2, :class => 'xxlarge'}
  .actions
    = f.button :submit, :class => 'primary'
    = link_to 'Cancel', project_goals_path(@project), :class => "btn"

= todo('Support particular month ranges for yield')

app/views/yield_goals/_table.html.haml
= table_for(yield_goals) do |t|
  = t.data do
    = t.cell :use_name, :heading => 'Product'
    = t.cell :amount_with_period, :heading => 'Amount'
    = t.cell :lead_time_string, :heading => 'Lead Time'
    = t.cell :details, :heading => 'Details', :cell_html => {:class => 'details'}
    - if can? :edit, @project
      = t.cell('', :cell_html => {:class => 'actions'}) {|goal| link_to('Edit', edit_project_yield_goal_path(@project, goal)) }
      = t.cell('', :cell_html => {:class => 'actions'}) {|goal| link_to('Remove', [@project, goal], :confirm => 'Are you sure?', :method => :delete) }
  - if can? :create, YieldGoal
    = table_link_footer t, 'Add Another', new_project_yield_goal_path(@project)